### ISSUE TITLE
How do i access the IP/FQDN of a vra7 machine?

### ISSUE THREAD

**Issue by mcascone** [terraform-providers/terraform-provider-vra7#14]
What is the resource attribute structure of the vra7 machines created via this provider? 

`"${vra7_deployment.<name>.ip}"` doesn't work. 

Thanks!

**Comment by Prativa20** [comment]
Hi @mcascone , we are working on it. Will update soon.

**Comment by mcascone** [comment]
Thanks for the reply. I'd been looking for this thread to update that I'd figured it out:

The key was understanding that my instance of vRA is set up so that the VMs are called `vSphere_Machine_1`. It's right there in the UI, as Component Name.

There were definitely some mental leaps involved, and I'm sure I had to have seen all the other examples and made all the mistakes i did in order for my brain to put it all together at that moment. Whatever the mechanism, this code now WORKS:

_in resource block_
```
resource_configuration {
    vSphere_Machine_1.name = ""
  }
```

_in provisioner block_
```
    connection {
      host = "${self.resource_configuration.vSphere_Machine_1.name}"
}
```

For others coming to this with the same question, you are looking for the Component Name in your vRa item's machine listing. 
![vra1](https://user-images.githubusercontent.com/8335079/58903893-11b47400-86cc-11e9-9cc8-0c47c45e52bf.jpg)
